# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {F:/Vivado labs/sys3_lab1_myversion/lab5.cache/wt} [current_project]
set_property parent.project_path {F:/Vivado labs/sys3_lab1_myversion/lab5.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {f:/Vivado labs/sys3_lab1_myversion/lab5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{F:/Vivado labs/sys3_lab1_myversion/code/coe/lab2-rom.coe}}
add_files {{F:/Vivado labs/sys3_lab1_myversion/code/coe/lab2-ram.coe}}
add_files {{F:/Vivado labs/sys3_lab1_myversion/lab2/lab2-ram.coe}}
add_files {{F:/Vivado labs/sys3_lab1_myversion/lab2/lab2-rom.coe}}
read_verilog {{F:/Vivado labs/sys3_lab1_myversion/code/src/AluOp.vh}}
set_property file_type "Verilog Header" [get_files {{F:/Vivado labs/sys3_lab1_myversion/code/src/AluOp.vh}}]
read_verilog -library xil_defaultlib -sv {
  {F:/Vivado labs/sys3_lab1_myversion/code/src/IO_Manager.sv}
  {F:/Vivado labs/sys3_lab1_myversion/code/src/Top.sv}
}
read_verilog -library xil_defaultlib {
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/ALU.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/CSR.v}
  {F:/Vivado labs/sys3_lab1_myversion/code/src/Core.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/EX_MEM_reg.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/ID_EX_reg.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/IF_ID_reg.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/MEM_WB_reg.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/Register.v}
  {F:/Vivado labs/sys3_lab1_myversion/code/src/SCPU.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/branch_prediction_unit.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/forwarding_unit.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/hazard_detection_unit.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/immgen.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/mycontrol.v}
  {F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/new/pc.v}
}
read_ip -quiet {{F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/ip/Ram/Ram.xci}}
set_property used_in_implementation false [get_files -all {{f:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/ip/Ram/Ram_ooc.xdc}}]

read_ip -quiet {{F:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/ip/Rom_1/Rom.xci}}
set_property used_in_implementation false [get_files -all {{f:/Vivado labs/sys3_lab1_myversion/lab5.srcs/sources_1/ip/Rom_1/Rom_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{F:/Vivado labs/sys3_lab1_myversion/code/constrs/nexys_a7.xdc}}
set_property used_in_implementation false [get_files {{F:/Vivado labs/sys3_lab1_myversion/code/constrs/nexys_a7.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
