webtalk_init -webtalk_dir F:/Vivado labs/Xpart-RV64/lab5.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul  3 22:10:59 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a08174f437f553178fde4c0ea8ea72a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a8bcf7b3c9fd4db49a7c473bbe949b2f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "474" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "317 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "102 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1711" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "68" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "91280_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2733431028 -regid "" -xml F:/Vivado labs/Xpart-RV64/lab5.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Vivado labs/Xpart-RV64/lab5.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Vivado labs/Xpart-RV64/lab5.sim/sim_1/behav/xsim/xsim.dir/Core_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
