# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/23882/Desktop/Xpart-RV64-main/lab5.srcs/sources_1/ip/Rom_1/Rom.xci
# IP: The module: 'Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23882/Desktop/Xpart-RV64-main/lab5.srcs/sources_1/ip/Rom_1/Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/23882/Desktop/Xpart-RV64-main/lab5.srcs/sources_1/ip/Rom_1/Rom.xci
# IP: The module: 'Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23882/Desktop/Xpart-RV64-main/lab5.srcs/sources_1/ip/Rom_1/Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
